# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: tobyn.nicholls@diamond.ac.uk, philip.smith@diamond.ac.uk
author_name: Tobyn Nicholls, Phil Smith
component_lifecycle: production
component_owner: group:default/high-level-apps
component_type: user-interface
description: Accelerator Toolbox Interface for Pytac
distribution_name: atip
docker: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: atip
pypi: true
repo_name: atip
type_checker: pyright
