dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run python -m pytest test --cov-report term-missing --cov=atip
  - pipenv run flake8 --ignore=E501,W504
  - pipenv run sphinx-build -b html -ETW docs docs/_build/html
  - pipenv run python setup.py bdist_wheel

after_success:
  - pipenv run coveralls
