dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install virtualenv
  - python -m virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

script:
  - python -m pytest test --cov-report term-missing --cov=atip
  - flake8 --ignore=E501,W504
  - sphinx-build -b html -ETW docs docs/_build/html

after_success:
  - coveralls
