apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: atip
  title: atip
  description: Accelerator Toolbox Interface for Pytac
spec:
  type: library
  lifecycle: production
  owner: group:default/high-level-apps
