#!/bin/sh

PYIOC_VERSION=2-15
EPICS_VERSION=R3.14.12.7
PYIOC=/dls_sw/prod/$EPICS_VERSION/support/pythonIoc/$PYIOC_VERSION/pythonIoc

export EPICS_CA_SERVER_PORT=6064
export EPICS_CAS_SERVER_PORT=6064

cd "$(dirname "$0")/virtac"
exec $PYIOC atip_ioc_entry.py "$@"
