#!/bin/sh

PYIOC_VERSION=2-11
EPICS_VERSION=R3.14.12.3
PYIOC=/dls_sw/prod/$EPICS_VERSION/support/pythonSoftIoc/$PYIOC_VERSION/pythonIoc

export EPICS_CA_SERVER_PORT=6064
export EPICS_CAS_SERVER_PORT=6064

cd "$(dirname "$0")/ioc"
exec $PYIOC atip_ioc_entry.py "$@"
