name: atip
dependencies:
- python=3.6
- numpy>=1.10
- scipy>=0.16
- pip:
  - cothread
  - git+https://github.com/dls-controls/pytac.git
  - --extra-index-url=https://test.pypi.org/simple/
  - accelerator-toolbox
